[package]
name = "reddist"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
tokio = {version = "1.41.0", features = [
    "rt-multi-thread",
    "macros",
    "net",
    "io-util",
    "sync",
]}
log = "0.4.22"
env_logger = "0.11.5"
